name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run basic tests
      run: ./check.sh -v
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - uses: giraffate/clippy-action@v1
      with:
        reporter: github-pr-review
  extra:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run extra tests
      run: |
        cargo install cargo-tomlfmt
        ./check-extra.sh -v
  msrv:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - uses: dtolnay/rust-toolchain@1.85.0
    - uses: dtolnay/rust-toolchain@1.86.0
    - uses: Swatinem/rust-cache@v2
    - name: Run tests with MSRV
      run: ./check-msrv.sh -v
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Test yash-arith
      run: cargo test --all-features --package yash-arith
    - name: Test yash-executor
      run: cargo test --all-features --package yash-executor
    - name: Test yash-fnmatch
      run: cargo test --all-features --package yash-fnmatch
    - name: Test yash-quote
      run: cargo test --all-features --package yash-quote
    - name: Test yash-syntax
      run: cargo test --all-features --package yash-syntax
    - name: Test yash-env
      run: cargo test --all-features --package yash-env
    - name: Test yash-env-test-helper
      run: cargo test --all-features --package yash-env-test-helper
    - name: Test yash-semantics
      run: cargo test --all-features --package yash-semantics
    - name: Test yash-prompt
      run: cargo test --all-features --package yash-prompt
    - name: Test yash-builtin
      run: cargo test --all-features --package yash-builtin
  summarize:
    runs-on: ubuntu-latest
    needs: [check, clippy, extra, msrv, windows]
    if: ${{ always() }}
    steps:
    - uses: Kesin11/actions-timeline@v2
